#standardSQL
-- Generated by src/collect_gdelt.py. Review before execution.
-- Unit: one official EM-DAT DisNo. x Indian state/UT event.
-- Deduplication: exact GDELT DocumentIdentifier; one identifier per state is
-- assigned to the nearest event onset when windows overlap.
WITH event_windows AS (
  SELECT * FROM UNNEST([
    STRUCT('E001' AS event_id, 'Jammu and Kashmir' AS state, '2015-0107-IND' AS source_record_id, DATE '2015-03-20' AS onset_date, DATE '2015-03-20' AS query_start, DATE '2015-06-21' AS query_end, ['jammu and kashmir', 'jammu & kashmir', 'jammu kashmir'] AS location_terms),
    STRUCT('E002' AS event_id, 'Tamil Nadu' AS state, '2015-0207-IND' AS source_record_id, DATE '2015-05-17' AS onset_date, DATE '2015-05-17' AS query_start, DATE '2015-08-18' AS query_end, ['tamil nadu', 'tamilnadu', 'virudunagar'] AS location_terms),
    STRUCT('E003' AS event_id, 'Gujarat' AS state, '2015-0249-IND' AS source_record_id, DATE '2015-06-19' AS onset_date, DATE '2015-06-19' AS query_start, DATE '2015-09-20' AS query_end, ['gujarat', 'morbi'] AS location_terms),
    STRUCT('E004' AS event_id, 'Maharashtra' AS state, '2015-0249-IND' AS source_record_id, DATE '2015-06-19' AS onset_date, DATE '2015-06-19' AS query_start, DATE '2015-09-20' AS query_end, ['maharashtra'] AS location_terms),
    STRUCT('E005' AS event_id, 'West Bengal' AS state, '2015-0253-IND' AS source_record_id, DATE '2015-06-23' AS onset_date, DATE '2015-06-23' AS query_start, DATE '2015-09-24' AS query_end, ['west bengal', 'darjiling'] AS location_terms),
    STRUCT('E006' AS event_id, 'Arunachal Pradesh' AS state, '2015-0333-IND' AS source_record_id, DATE '2015-07-07' AS onset_date, DATE '2015-07-07' AS query_start, DATE '2015-10-08' AS query_end, ['arunachal pradesh'] AS location_terms),
    STRUCT('E007' AS event_id, 'Haryana' AS state, '2015-0333-IND' AS source_record_id, DATE '2015-07-07' AS onset_date, DATE '2015-07-07' AS query_start, DATE '2015-10-08' AS query_end, ['haryana'] AS location_terms),
    STRUCT('E008' AS event_id, 'Himachal Pradesh' AS state, '2015-0333-IND' AS source_record_id, DATE '2015-07-07' AS onset_date, DATE '2015-07-07' AS query_start, DATE '2015-10-08' AS query_end, ['himachal pradesh'] AS location_terms),
    STRUCT('E009' AS event_id, 'Jammu and Kashmir' AS state, '2015-0333-IND' AS source_record_id, DATE '2015-07-07' AS onset_date, DATE '2015-07-07' AS query_start, DATE '2015-10-08' AS query_end, ['jammu and kashmir', 'jammu & kashmir', 'jammu kashmir'] AS location_terms),
    STRUCT('E010' AS event_id, 'Punjab' AS state, '2015-0333-IND' AS source_record_id, DATE '2015-07-07' AS onset_date, DATE '2015-07-07' AS query_start, DATE '2015-10-08' AS query_end, ['punjab'] AS location_terms),
    STRUCT('E011' AS event_id, 'Rajasthan' AS state, '2015-0333-IND' AS source_record_id, DATE '2015-07-07' AS onset_date, DATE '2015-07-07' AS query_start, DATE '2015-10-08' AS query_end, ['rajasthan'] AS location_terms),
    STRUCT('E012' AS event_id, 'Uttar Pradesh' AS state, '2015-0333-IND' AS source_record_id, DATE '2015-07-07' AS onset_date, DATE '2015-07-07' AS query_start, DATE '2015-10-08' AS query_end, ['uttar pradesh'] AS location_terms),
    STRUCT('E013' AS event_id, 'Uttarakhand' AS state, '2015-0333-IND' AS source_record_id, DATE '2015-07-07' AS onset_date, DATE '2015-07-07' AS query_start, DATE '2015-10-08' AS query_end, ['uttarakhand', 'uttaranchal'] AS location_terms),
    STRUCT('E014' AS event_id, 'Arunachal Pradesh' AS state, '2015-0413-IND' AS source_record_id, DATE '2015-07-14' AS onset_date, DATE '2015-07-14' AS query_start, DATE '2015-10-15' AS query_end, ['arunachal pradesh'] AS location_terms),
    STRUCT('E015' AS event_id, 'Assam' AS state, '2015-0413-IND' AS source_record_id, DATE '2015-07-14' AS onset_date, DATE '2015-07-14' AS query_start, DATE '2015-10-15' AS query_end, ['assam', 'kokrajhar'] AS location_terms),
    STRUCT('E016' AS event_id, 'Assam' AS state, '2015-0317-IND' AS source_record_id, DATE '2015-07-15' AS onset_date, DATE '2015-07-15' AS query_start, DATE '2015-10-16' AS query_end, ['assam', 'goalpara'] AS location_terms),
    STRUCT('E017' AS event_id, 'Gujarat' AS state, '2015-0317-IND' AS source_record_id, DATE '2015-07-15' AS onset_date, DATE '2015-07-15' AS query_start, DATE '2015-10-16' AS query_end, ['gujarat', 'kachchh'] AS location_terms),
    STRUCT('E018' AS event_id, 'Madhya Pradesh' AS state, '2015-0317-IND' AS source_record_id, DATE '2015-07-15' AS onset_date, DATE '2015-07-15' AS query_start, DATE '2015-10-16' AS query_end, ['madhya pradesh'] AS location_terms),
    STRUCT('E019' AS event_id, 'Manipur' AS state, '2015-0317-IND' AS source_record_id, DATE '2015-07-15' AS onset_date, DATE '2015-07-15' AS query_start, DATE '2015-10-16' AS query_end, ['manipur'] AS location_terms),
    STRUCT('E020' AS event_id, 'Odisha' AS state, '2015-0317-IND' AS source_record_id, DATE '2015-07-15' AS onset_date, DATE '2015-07-15' AS query_start, DATE '2015-10-16' AS query_end, ['odisha', 'orissa'] AS location_terms),
    STRUCT('E021' AS event_id, 'Rajasthan' AS state, '2015-0317-IND' AS source_record_id, DATE '2015-07-15' AS onset_date, DATE '2015-07-15' AS query_start, DATE '2015-10-16' AS query_end, ['rajasthan'] AS location_terms),
    STRUCT('E022' AS event_id, 'West Bengal' AS state, '2015-0317-IND' AS source_record_id, DATE '2015-07-15' AS onset_date, DATE '2015-07-15' AS query_start, DATE '2015-10-16' AS query_end, ['west bengal', 'maldah'] AS location_terms),
    STRUCT('E023' AS event_id, 'Assam' AS state, '2015-0374-IND' AS source_record_id, DATE '2015-08-13' AS onset_date, DATE '2015-08-13' AS query_start, DATE '2015-11-14' AS query_end, ['assam'] AS location_terms),
    STRUCT('E024' AS event_id, 'Assam' AS state, '2015-0406-IND' AS source_record_id, DATE '2015-08-28' AS onset_date, DATE '2015-08-28' AS query_start, DATE '2015-11-29' AS query_end, ['assam', 'barpeta'] AS location_terms),
    STRUCT('E025' AS event_id, 'Andhra Pradesh' AS state, '2015-0504-IND' AS source_record_id, DATE '2015-11-08' AS onset_date, DATE '2015-11-08' AS query_start, DATE '2016-02-09' AS query_end, ['andhra pradesh', 'y.s.r.'] AS location_terms),
    STRUCT('E026' AS event_id, 'Puducherry' AS state, '2015-0504-IND' AS source_record_id, DATE '2015-11-08' AS onset_date, DATE '2015-11-08' AS query_start, DATE '2016-02-09' AS query_end, ['puducherry', 'pondicherry'] AS location_terms),
    STRUCT('E027' AS event_id, 'Tamil Nadu' AS state, '2015-0504-IND' AS source_record_id, DATE '2015-11-08' AS onset_date, DATE '2015-11-08' AS query_start, DATE '2016-02-09' AS query_end, ['tamil nadu', 'tamilnadu', 'nagappattinam'] AS location_terms),
    STRUCT('E028' AS event_id, 'Arunachal Pradesh' AS state, '2016-0139-IND' AS source_record_id, DATE '2016-04-22' AS onset_date, DATE '2016-04-22' AS query_start, DATE '2016-07-24' AS query_end, ['arunachal pradesh'] AS location_terms),
    STRUCT('E029' AS event_id, 'Assam' AS state, '2016-0139-IND' AS source_record_id, DATE '2016-04-22' AS onset_date, DATE '2016-04-22' AS query_start, DATE '2016-07-24' AS query_end, ['assam'] AS location_terms),
    STRUCT('E030' AS event_id, 'Nagaland' AS state, '2016-0139-IND' AS source_record_id, DATE '2016-04-22' AS onset_date, DATE '2016-04-22' AS query_start, DATE '2016-07-24' AS query_end, ['nagaland'] AS location_terms),
    STRUCT('E031' AS event_id, 'Arunachal Pradesh' AS state, '2016-0239-IND' AS source_record_id, DATE '2016-06-25' AS onset_date, DATE '2016-06-25' AS query_start, DATE '2016-09-26' AS query_end, ['arunachal pradesh'] AS location_terms),
    STRUCT('E032' AS event_id, 'Assam' AS state, '2016-0239-IND' AS source_record_id, DATE '2016-06-25' AS onset_date, DATE '2016-06-25' AS query_start, DATE '2016-09-26' AS query_end, ['assam'] AS location_terms),
    STRUCT('E033' AS event_id, 'Uttarakhand' AS state, '2016-0239-IND' AS source_record_id, DATE '2016-06-25' AS onset_date, DATE '2016-06-25' AS query_start, DATE '2016-09-26' AS query_end, ['uttarakhand', 'uttaranchal', 'chamoli'] AS location_terms),
    STRUCT('E034' AS event_id, 'Madhya Pradesh' AS state, '2016-0276-IND' AS source_record_id, DATE '2016-07-09' AS onset_date, DATE '2016-07-09' AS query_start, DATE '2016-10-10' AS query_end, ['madhya pradesh', 'damoh'] AS location_terms),
    STRUCT('E035' AS event_id, 'Bihar' AS state, '2016-0271-IND' AS source_record_id, DATE '2016-07-15' AS onset_date, DATE '2016-07-15' AS query_start, DATE '2016-10-16' AS query_end, ['bihar'] AS location_terms),
    STRUCT('E036' AS event_id, 'Uttar Pradesh' AS state, '2016-0271-IND' AS source_record_id, DATE '2016-07-15' AS onset_date, DATE '2016-07-15' AS query_start, DATE '2016-10-16' AS query_end, ['uttar pradesh'] AS location_terms),
    STRUCT('E037' AS event_id, 'Assam' AS state, '2016-0554-IND' AS source_record_id, DATE '2016-07-17' AS onset_date, DATE '2016-07-17' AS query_start, DATE '2016-10-18' AS query_end, ['assam', 'golaghat'] AS location_terms),
    STRUCT('E038' AS event_id, 'Assam' AS state, '2016-0267-IND' AS source_record_id, DATE '2016-07-28' AS onset_date, DATE '2016-07-28' AS query_start, DATE '2016-10-29' AS query_end, ['assam', 'barpeta'] AS location_terms),
    STRUCT('E039' AS event_id, 'Gujarat' AS state, '2016-0304-IND' AS source_record_id, DATE '2016-08-01' AS onset_date, DATE '2016-08-01' AS query_start, DATE '2016-11-02' AS query_end, ['gujarat', 'navsari'] AS location_terms),
    STRUCT('E040' AS event_id, 'Maharashtra' AS state, '2016-0304-IND' AS source_record_id, DATE '2016-08-01' AS onset_date, DATE '2016-08-01' AS query_start, DATE '2016-11-02' AS query_end, ['maharashtra', 'kolhapur'] AS location_terms),
    STRUCT('E041' AS event_id, 'Andhra Pradesh' AS state, '2016-0391-IND' AS source_record_id, DATE '2016-09-21' AS onset_date, DATE '2016-09-21' AS query_start, DATE '2016-12-23' AS query_end, ['andhra pradesh'] AS location_terms),
    STRUCT('E042' AS event_id, 'Telangana' AS state, '2016-0391-IND' AS source_record_id, DATE '2016-09-21' AS onset_date, DATE '2016-09-21' AS query_start, DATE '2016-12-23' AS query_end, ['telangana'] AS location_terms),
    STRUCT('E043' AS event_id, 'Gujarat' AS state, '2017-0257-IND' AS source_record_id, DATE '2017-06-01' AS onset_date, DATE '2017-06-01' AS query_start, DATE '2017-09-02' AS query_end, ['gujarat'] AS location_terms),
    STRUCT('E044' AS event_id, 'Gujarat' AS state, '2017-0294-IND' AS source_record_id, DATE '2017-06-01' AS onset_date, DATE '2017-06-01' AS query_start, DATE '2017-09-02' AS query_end, ['gujarat'] AS location_terms),
    STRUCT('E045' AS event_id, 'Rajasthan' AS state, '2017-0294-IND' AS source_record_id, DATE '2017-06-01' AS onset_date, DATE '2017-06-01' AS query_start, DATE '2017-09-02' AS query_end, ['rajasthan'] AS location_terms),
    STRUCT('E046' AS event_id, 'West Bengal' AS state, '2017-0294-IND' AS source_record_id, DATE '2017-06-01' AS onset_date, DATE '2017-06-01' AS query_start, DATE '2017-09-02' AS query_end, ['west bengal'] AS location_terms),
    STRUCT('E047' AS event_id, 'Assam' AS state, '2017-0180-IND' AS source_record_id, DATE '2017-06-04' AS onset_date, DATE '2017-06-04' AS query_start, DATE '2017-09-05' AS query_end, ['assam'] AS location_terms),
    STRUCT('E048' AS event_id, 'Jharkhand' AS state, '2017-0180-IND' AS source_record_id, DATE '2017-06-04' AS onset_date, DATE '2017-06-04' AS query_start, DATE '2017-09-05' AS query_end, ['jharkhand'] AS location_terms),
    STRUCT('E049' AS event_id, 'Manipur' AS state, '2017-0180-IND' AS source_record_id, DATE '2017-06-04' AS onset_date, DATE '2017-06-04' AS query_start, DATE '2017-09-05' AS query_end, ['manipur'] AS location_terms),
    STRUCT('E050' AS event_id, 'Nagaland' AS state, '2017-0180-IND' AS source_record_id, DATE '2017-06-04' AS onset_date, DATE '2017-06-04' AS query_start, DATE '2017-09-05' AS query_end, ['nagaland'] AS location_terms),
    STRUCT('E051' AS event_id, 'Assam' AS state, '2017-0289-IND' AS source_record_id, DATE '2017-06-25' AS onset_date, DATE '2017-06-25' AS query_start, DATE '2017-09-26' AS query_end, ['assam', 'barpeta'] AS location_terms),
    STRUCT('E052' AS event_id, 'Manipur' AS state, '2017-0290-IND' AS source_record_id, DATE '2017-07-01' AS onset_date, DATE '2017-07-01' AS query_start, DATE '2017-10-02' AS query_end, ['manipur', 'bishnupur'] AS location_terms),
    STRUCT('E053' AS event_id, 'Bihar' AS state, '2017-0342-IND' AS source_record_id, DATE '2017-08-11' AS onset_date, DATE '2017-08-11' AS query_start, DATE '2017-11-12' AS query_end, ['bihar', 'araria'] AS location_terms),
    STRUCT('E054' AS event_id, 'Uttar Pradesh' AS state, '2017-0342-IND' AS source_record_id, DATE '2017-08-11' AS onset_date, DATE '2017-08-11' AS query_start, DATE '2017-11-12' AS query_end, ['uttar pradesh'] AS location_terms),
    STRUCT('E055' AS event_id, 'West Bengal' AS state, '2017-0342-IND' AS source_record_id, DATE '2017-08-11' AS onset_date, DATE '2017-08-11' AS query_start, DATE '2017-11-12' AS query_end, ['west bengal'] AS location_terms),
    STRUCT('E056' AS event_id, 'Uttar Pradesh' AS state, '2017-0517-IND' AS source_record_id, DATE '2017-08-16' AS onset_date, DATE '2017-08-16' AS query_start, DATE '2017-11-17' AS query_end, ['uttar pradesh', 'bahraich'] AS location_terms),
    STRUCT('E057' AS event_id, 'Maharashtra' AS state, '2017-0364-IND' AS source_record_id, DATE '2017-08-29' AS onset_date, DATE '2017-08-29' AS query_start, DATE '2017-11-30' AS query_end, ['maharashtra', 'mumbai city'] AS location_terms),
    STRUCT('E058' AS event_id, 'Tamil Nadu' AS state, '2017-0495-IND' AS source_record_id, DATE '2017-10-30' AS onset_date, DATE '2017-10-30' AS query_start, DATE '2018-01-31' AS query_end, ['tamil nadu', 'tamilnadu', 'chennai'] AS location_terms),
    STRUCT('E059' AS event_id, 'Tripura' AS state, '2018-0213-IND' AS source_record_id, DATE '2018-05-17' AS onset_date, DATE '2018-05-17' AS query_start, DATE '2018-08-18' AS query_end, ['tripura'] AS location_terms),
    STRUCT('E060' AS event_id, 'Karnataka' AS state, '2018-0216-IND' AS source_record_id, DATE '2018-05-29' AS onset_date, DATE '2018-05-29' AS query_start, DATE '2018-08-30' AS query_end, ['karnataka', 'bangalore', 'dakshina kannada'] AS location_terms),
    STRUCT('E061' AS event_id, 'Assam' AS state, '2018-0205-IND' AS source_record_id, DATE '2018-06-22' AS onset_date, DATE '2018-06-22' AS query_start, DATE '2018-09-23' AS query_end, ['assam'] AS location_terms),
    STRUCT('E062' AS event_id, 'Gujarat' AS state, '2018-0205-IND' AS source_record_id, DATE '2018-06-22' AS onset_date, DATE '2018-06-22' AS query_start, DATE '2018-09-23' AS query_end, ['gujarat'] AS location_terms),
    STRUCT('E063' AS event_id, 'Maharashtra' AS state, '2018-0205-IND' AS source_record_id, DATE '2018-06-22' AS onset_date, DATE '2018-06-22' AS query_start, DATE '2018-09-23' AS query_end, ['maharashtra'] AS location_terms),
    STRUCT('E064' AS event_id, 'Odisha' AS state, '2018-0286-IND' AS source_record_id, DATE '2018-07-20' AS onset_date, DATE '2018-07-20' AS query_start, DATE '2018-10-21' AS query_end, ['odisha', 'orissa'] AS location_terms),
    STRUCT('E065' AS event_id, 'Rajasthan' AS state, '2018-0267-IND' AS source_record_id, DATE '2018-07-26' AS onset_date, DATE '2018-07-26' AS query_start, DATE '2018-10-27' AS query_end, ['rajasthan'] AS location_terms),
    STRUCT('E066' AS event_id, 'Uttar Pradesh' AS state, '2018-0267-IND' AS source_record_id, DATE '2018-07-26' AS onset_date, DATE '2018-07-26' AS query_start, DATE '2018-10-27' AS query_end, ['uttar pradesh'] AS location_terms),
    STRUCT('E067' AS event_id, 'Assam' AS state, '2018-0345-IND' AS source_record_id, DATE '2018-08-02' AS onset_date, DATE '2018-08-02' AS query_start, DATE '2018-11-03' AS query_end, ['assam', 'golaghat'] AS location_terms),
    STRUCT('E068' AS event_id, 'West Bengal' AS state, '2018-0345-IND' AS source_record_id, DATE '2018-08-02' AS onset_date, DATE '2018-08-02' AS query_start, DATE '2018-11-03' AS query_end, ['west bengal'] AS location_terms),
    STRUCT('E069' AS event_id, 'Assam' AS state, '2018-0295-IND' AS source_record_id, DATE '2018-08-07' AS onset_date, DATE '2018-08-07' AS query_start, DATE '2018-11-08' AS query_end, ['assam'] AS location_terms),
    STRUCT('E070' AS event_id, 'Himachal Pradesh' AS state, '2018-0295-IND' AS source_record_id, DATE '2018-08-07' AS onset_date, DATE '2018-08-07' AS query_start, DATE '2018-11-08' AS query_end, ['himachal pradesh'] AS location_terms),
    STRUCT('E071' AS event_id, 'Kerala' AS state, '2018-0295-IND' AS source_record_id, DATE '2018-08-07' AS onset_date, DATE '2018-08-07' AS query_start, DATE '2018-11-08' AS query_end, ['kerala', 'thrissur'] AS location_terms),
    STRUCT('E072' AS event_id, 'Maharashtra' AS state, '2018-0295-IND' AS source_record_id, DATE '2018-08-07' AS onset_date, DATE '2018-08-07' AS query_start, DATE '2018-11-08' AS query_end, ['maharashtra'] AS location_terms),
    STRUCT('E073' AS event_id, 'Nagaland' AS state, '2018-0295-IND' AS source_record_id, DATE '2018-08-07' AS onset_date, DATE '2018-08-07' AS query_start, DATE '2018-11-08' AS query_end, ['nagaland'] AS location_terms),
    STRUCT('E074' AS event_id, 'Odisha' AS state, '2018-0295-IND' AS source_record_id, DATE '2018-08-07' AS onset_date, DATE '2018-08-07' AS query_start, DATE '2018-11-08' AS query_end, ['odisha', 'orissa'] AS location_terms),
    STRUCT('E075' AS event_id, 'Uttar Pradesh' AS state, '2018-0295-IND' AS source_record_id, DATE '2018-08-07' AS onset_date, DATE '2018-08-07' AS query_start, DATE '2018-11-08' AS query_end, ['uttar pradesh'] AS location_terms),
    STRUCT('E076' AS event_id, 'West Bengal' AS state, '2018-0295-IND' AS source_record_id, DATE '2018-08-07' AS onset_date, DATE '2018-08-07' AS query_start, DATE '2018-11-08' AS query_end, ['west bengal'] AS location_terms),
    STRUCT('E077' AS event_id, 'Uttar Pradesh' AS state, '2018-0370-IND' AS source_record_id, DATE '2018-09-01' AS onset_date, DATE '2018-09-01' AS query_start, DATE '2018-12-03' AS query_end, ['uttar pradesh'] AS location_terms),
    STRUCT('E078' AS event_id, 'Haryana' AS state, '2018-0372-IND' AS source_record_id, DATE '2018-09-23' AS onset_date, DATE '2018-09-23' AS query_start, DATE '2018-12-25' AS query_end, ['haryana'] AS location_terms),
    STRUCT('E079' AS event_id, 'Punjab' AS state, '2018-0372-IND' AS source_record_id, DATE '2018-09-23' AS onset_date, DATE '2018-09-23' AS query_start, DATE '2018-12-25' AS query_end, ['punjab'] AS location_terms),
    STRUCT('E080' AS event_id, 'Maharashtra' AS state, '2019-0288-IND' AS source_record_id, DATE '2019-06-28' AS onset_date, DATE '2019-06-28' AS query_start, DATE '2019-09-29' AS query_end, ['maharashtra', 'mumbai city'] AS location_terms),
    STRUCT('E081' AS event_id, 'Assam' AS state, '2019-0331-IND' AS source_record_id, DATE '2019-07-14' AS onset_date, DATE '2019-07-14' AS query_start, DATE '2019-10-15' AS query_end, ['assam'] AS location_terms),
    STRUCT('E082' AS event_id, 'Bihar' AS state, '2019-0331-IND' AS source_record_id, DATE '2019-07-14' AS onset_date, DATE '2019-07-14' AS query_start, DATE '2019-10-15' AS query_end, ['bihar', 'katihar'] AS location_terms),
    STRUCT('E083' AS event_id, 'Himachal Pradesh' AS state, '2019-0331-IND' AS source_record_id, DATE '2019-07-14' AS onset_date, DATE '2019-07-14' AS query_start, DATE '2019-10-15' AS query_end, ['himachal pradesh'] AS location_terms),
    STRUCT('E084' AS event_id, 'Karnataka' AS state, '2019-0331-IND' AS source_record_id, DATE '2019-07-14' AS onset_date, DATE '2019-07-14' AS query_start, DATE '2019-10-15' AS query_end, ['karnataka', 'bangalore'] AS location_terms),
    STRUCT('E086' AS event_id, 'Maharashtra' AS state, '2019-0331-IND' AS source_record_id, DATE '2019-07-14' AS onset_date, DATE '2019-07-14' AS query_start, DATE '2019-10-15' AS query_end, ['maharashtra'] AS location_terms),
    STRUCT('E094' AS event_id, 'Maharashtra' AS state, '2019-0383-IND' AS source_record_id, DATE '2019-08-12' AS onset_date, DATE '2019-08-12' AS query_start, DATE '2019-11-13' AS query_end, ['maharashtra'] AS location_terms)
  ])
),
gkg_raw AS (
  SELECT
    PARSE_TIMESTAMP('%Y%m%d%H%M%S', CAST(`DATE` AS STRING), 'UTC') AS published_at,
    DocumentIdentifier AS url,
    TRIM(DocumentIdentifier) AS normalized_url,
    LOWER(COALESCE(V2Locations, '')) AS locations_lower,
    CAST('' AS STRING) AS title_lower,
    CASE
      WHEN REGEXP_EXTRACT(COALESCE(TranslationInfo, ''), r'srclc:([a-z]{3})') = 'eng' THEN 'en'
      ELSE COALESCE(
        REGEXP_EXTRACT(COALESCE(TranslationInfo, ''), r'srclc:([a-z]{3})'),
        'en'
      )
    END AS source_lang
  FROM `gdelt-bq.gdeltv2.gkg_partitioned`
  WHERE (
        (_PARTITIONTIME >= TIMESTAMP('2015-03-20') AND _PARTITIONTIME < TIMESTAMP('2016-02-10'))
        OR (_PARTITIONTIME >= TIMESTAMP('2016-04-22') AND _PARTITIONTIME < TIMESTAMP('2016-12-24'))
        OR (_PARTITIONTIME >= TIMESTAMP('2017-06-01') AND _PARTITIONTIME < TIMESTAMP('2018-02-01'))
        OR (_PARTITIONTIME >= TIMESTAMP('2018-05-17') AND _PARTITIONTIME < TIMESTAMP('2018-12-26'))
        OR (_PARTITIONTIME >= TIMESTAMP('2019-06-28') AND _PARTITIONTIME < TIMESTAMP('2019-11-14'))
      )
      AND `DATE` >= 20150320000000
      AND `DATE` <= 20191113235959
      AND DocumentIdentifier IS NOT NULL
      AND EXISTS (
        SELECT 1
        FROM UNNEST(SPLIT(COALESCE(V2Locations, ''), ';')) AS location_ref
        WHERE UPPER(SPLIT(location_ref, '#')[SAFE_OFFSET(2)]) = 'IN'
      )
      AND EXISTS (
        SELECT 1
        FROM UNNEST(SPLIT(COALESCE(V2Themes, ''), ';')) AS theme_ref
        WHERE SPLIT(theme_ref, ',')[SAFE_OFFSET(0)] IN UNNEST(['NATURAL_DISASTER_FLOOD', 'NATURAL_DISASTER_FLOODING', 'NATURAL_DISASTER_FLOODS', 'NATURAL_DISASTER_FLOODED', 'NATURAL_DISASTER_FLOODED_AREAS', 'NATURAL_DISASTER_FLOODED_ROAD', 'NATURAL_DISASTER_FLOODED_ROADS', 'NATURAL_DISASTER_FLOODWATER', 'NATURAL_DISASTER_FLOODWATERS', 'NATURAL_DISASTER_FLOOD_WARNING', 'NATURAL_DISASTER_FLOOD_WATER', 'NATURAL_DISASTER_FLOOD_WATERS', 'NATURAL_DISASTER_FLASH_FLOOD', 'NATURAL_DISASTER_FLASH_FLOODS'])
      )
),
gkg AS (
  SELECT *
  FROM gkg_raw
  WHERE source_lang IN UNNEST(['en', 'ara', 'ben', 'guj', 'hin', 'kan', 'mal', 'mar', 'nep', 'ori', 'pan', 'pus', 'snd', 'tam', 'tel', 'urd'])
),
candidate_matches AS (
  SELECT
    e.event_id,
    e.state,
    e.source_record_id,
    e.onset_date,
    g.*,
    ABS(DATE_DIFF(DATE(g.published_at), e.onset_date, DAY)) AS onset_distance
  FROM event_windows e
  JOIN gkg AS g
    ON DATE(g.published_at) BETWEEN e.query_start AND e.query_end
  WHERE (
     EXISTS (
       SELECT 1
       FROM UNNEST(SPLIT(g.locations_lower, ';')) AS location_ref
       CROSS JOIN UNNEST(e.location_terms) AS term
       WHERE SPLIT(location_ref, '#')[SAFE_OFFSET(2)] = 'in'
         AND EXISTS (
           SELECT 1
           FROM UNNEST(SPLIT(
             COALESCE(SPLIT(location_ref, '#')[SAFE_OFFSET(1)], ''), ','
           )) AS location_part
           WHERE TRIM(location_part) = term
         )
     )
     OR EXISTS (
       SELECT 1
       FROM UNNEST(e.location_terms) AS term
       WHERE STRPOS(
         CONCAT(' ', REGEXP_REPLACE(g.title_lower, r'[^a-z0-9]+', ' '), ' '),
         CONCAT(' ', REGEXP_REPLACE(term, r'[^a-z0-9]+', ' '), ' ')
       ) > 0
     )
   )
),
assigned AS (
  SELECT * EXCEPT(assignment_rank, onset_distance)
  FROM (
    SELECT *, ROW_NUMBER() OVER (
      PARTITION BY normalized_url, state
      ORDER BY onset_distance, onset_date, event_id, published_at, url
    ) AS assignment_rank
    FROM candidate_matches
  )
  WHERE assignment_rank = 1
),
language_stats AS (
  SELECT
    event_id,
    state,
    source_record_id,
    source_lang,
    COUNT(DISTINCT normalized_url) AS article_count,
    MIN(DATE(published_at)) AS first_article_date,
    MAX(DATE(published_at)) AS last_article_date
  FROM assigned
  GROUP BY event_id, state, source_record_id, source_lang
),
event_days AS (
  SELECT event_id, COUNT(DISTINCT DATE(published_at)) AS coverage_days
  FROM assigned
  GROUP BY event_id
)
SELECT
  e.event_id,
  e.state,
  e.source_record_id,
  COALESCE(s.source_lang, 'und') AS source_lang,
  COALESCE(s.article_count, 0) AS article_count,
  s.first_article_date,
  s.last_article_date,
  COALESCE(d.coverage_days, 0) AS coverage_days,
  COALESCE(d.coverage_days, 0) AS coverage_days_threshold_1
FROM event_windows e
LEFT JOIN language_stats s USING (event_id, state, source_record_id)
LEFT JOIN event_days d USING (event_id)
ORDER BY e.event_id, article_count DESC, source_lang
